# Generated by Django 4.2.7 on 2023-11-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_tooth_cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
