# Generated by Django 4.2.7 on 2023-11-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_tooth_cafe', '0002_rename_customers_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='Rather Not Say', max_length=15),
        ),
    ]
