# Generated by Django 4.2.7 on 2023-11-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_tooth_cafe', '0004_alter_customer_address_id_alter_customer_wishlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wishlist_id',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
