# Generated by Django 4.2.7 on 2023-11-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_tooth_cafe', '0007_category_discount_inventory_wishlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candy',
            name='price',
            field=models.IntegerField(),
        ),
    ]
