# Generated by Django 4.2.7 on 2023-11-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_tooth_cafe', '0009_candy_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
