# Generated by Django 4.2.7 on 2023-11-20 06:28

from django.db import migrations, models
import sweet_tooth_cafe.models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_tooth_cafe', '0010_remove_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='customers/default.png', null=True, upload_to=sweet_tooth_cafe.models.generate_unique_name),
        ),
    ]
