# Generated by Django 4.2.7 on 2023-11-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_tooth_cafe', '0012_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='customers/default.png', null=True, upload_to='customers'),
        ),
    ]
